encoding:           utf-8
lang:               zh-cn

# Site Information
title:              Epipolar
description:        a personal journal
url:                https://itsuhane.github.io
baseurl:            ''

### Site Configuration

# Collections
collections:
  datasets:
    output: true


# Assets
assets:
  styles:           /assets/styles
  fonts:            /assets/fonts
  scripts:          /assets/scripts
  images:           /assets/images

# Typesetting
markdown:           kramdown
highlighter:        rouge

# Permalinks and Pagination
permalink:          pretty
paginate:           5
paginate_path:      /page-:num/

# Plugins
plugins:            [ jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag ]

# Default Settings
defaults:
  - scope:
      path:       ""
      type:       posts
    values:
      layout:     "post"
      comment:    true # <-- change to false if you want comments off by-default
      tags:       []
  - scope:
      path:       notes
      type:       pages
    values:
      layout:     "docs-page"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
