# Dependencies
markdown:         kramdown
mathjax:          true

# Permalinks
permalink:        pretty

# Setup
title:            Epipolar
tagline:          ''
description:      'Currently a mirror of epipolar.tumblr.com, check back later.'
url:              https://itsuhane.github.io
baseurl:          /
img:              https://itsuhane.github.io/images

assets:
  styles:         https://itsuhane.github.io/assets/styles
  fonts:          https://itsuhane.github.io/assets/fonts
  scripts:        https://itsuhane.github.io/assets/scripts
  images:         https://itsuhane.github.io/assets/images

author:
  name:           'itsuhane'
  url:            https://github.com/itsuhane

paginate:         5

defaults:
-
  scope:
    path:         ""
    type:         "posts"
  values:
    layout:       "post"
    comment:      "true"
    tags:         []

