# Information
title:            Epipolar
url:              https://itsuhane.github.io
baseurl:          ""

assets:
  styles:         /assets/styles
  fonts:          /assets/fonts
  scripts:        /assets/scripts
  images:         /assets/images

author:
  name:           itsuhane
  url:            https://github.com/itsuhane
  email:          itsuhane@gmail.com
  phone:          (000) 000-0000
  address:        Zhejiang Univ.
  address2:       Hangzhou, China
  github:         itsuhane
  #twitter:
  #facebook:       facebook
  #instagram:      instagram
  #weibo:

# Config for Menu
menu:
  hidden:         false  # <-- change to true if you want menu hidden on loaded
  search:         false
  miniposts:      false
  contact:        false

defaults:
  - scope:
      path:       ""
      type:       "posts"
    values:
      layout:     "post"
      comment:    "true" # <-- change to false if you want comments off by-default
      tags:       []

# Dependencies
markdown:         kramdown
mathjax:          true

# Permalinks
permalink:        pretty

# Pagination
paginate:         6
paginate_path:    /page-:num/
